workspace:
  base: /go
  path: src/github.com/drone-plugins/drone-docker

pipeline:
  build:
    image: golang:1.9
    commands:
      - go get -u github.com/golang/dep/cmd/dep
      - dep ensure
      - sh .drone.sh

  publish_ecr:
    image: 258875347723.dkr.ecr.us-east-1.amazonaws.com/drone-plugin-docker-ecr
    repo: 258875347723.dkr.ecr.us-east-1.amazonaws.com/drone-plugin-docker-ecr
    registry: 258875347723.dkr.ecr.us-east-1.amazonaws.com
    region: us-east-1
    dockerfile: docker/ecr/Dockerfile
    tags: [ "latest", "17", "17.05" ]
    when:
      branch: master
      event: push